services:
  postgres:
    image: postgres:latest
    container_name: crabjudge_postgres
    restart: always
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: judge
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U api -d judge"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: crabjudge_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: crabjudge_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 10s
      retries: 5

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-dev
    command: ["cargo-watch", "-x", "run --bin api"]
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - cargo-target:/app/target
    environment:
      DATABASE_URL: postgres://api:123@postgres:5432/judge
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  worker-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-dev
    command: ["cargo-watch", "-x", "run --bin worker"]
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - cargo-target:/app/target
    environment:
      DATABASE_URL: "postgres://api:123@postgres:5432/judge"
      SQLX_OFFLINE: "true"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-dev
    command: ["sqlx", "migrate", "run"]
    environment:
      DATABASE_URL: postgres://api:123@postgres:5432/judge
    volumes:
      - ./migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  cargo-target:
