runtimeconfigs:
  "python:3.12":
    image : python:3.12-slim
    run : python /tmp/file
    timeout : 2
    memory : 67108864
  
  "node:20":
    image : node:20-alpine
    run : node /tmp/file
    timeout : 2
    memory : 67108864

  "gcc":
    image : frolvlad/alpine-gcc
    compile : gcc -x c /tmp/file -o /tmp/a.out
    run :  /tmp/a.out
    timeout : 2
    memory : 67108864

