[package]
name = "config_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
config = {workspace = true}
serde = {workspace  =true}


[dev-dependencies]
config_loader_derive = {path = "../config_loader_derive/"}
